config/routes.rb
TicTacToe::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root 'game#show'
  post 'update_game_board', to: 'game#update_game_board', as: :update_game_board
  get 'restart_game', to: 'game#restart_game', as: :restart_game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def show
  end

  def update_game_board
    GAME.move(params[:id][/\d/].to_i)
    redirect_to root_path
  end

  def restart_game
    GAME.clear
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
  def win(game)
    game.win? ? "Congratulations #{game.previous_turn.upcase}! You've won!" : check_possible_moves(game)
  end

  def check_possible_moves(game)
    game.remaining_moves == 0 ? "It's a draw!" : nil
  end

  def disabled?(box, game)
    game.current_turn == 'o' || win(game) || box != '-' ? true : false
  end

  def tic_tac_toe_row(game, row)
    rows = { one: [*0..2], two: [*3..5], three: [*6..8] }
    game.board.each_with_index.inject("<div id='row-#{row}'>") do |acc, (box, ind)|
      sub_tag = button_to box, { action: 'update_game_board', id: "button-#{ind}" }, form_class: 'button-to', disabled: disabled?(box, game)
      acc += rows[row].include?(ind) ? content_tag(:div, sub_tag, class: "grid box-#{ind}") : ''
    end.html_safe
  end
end

app/views/game/_game_board.html.haml
= hidden_field_tag :turn, GAME.current_turn
= hidden_field_tag :computer_move, GAME.computer_move
- [:one, :two, :three].each do |row|
  = tic_tac_toe_row(GAME, row)

app/views/game/show.html.haml
%div.col-md-6.col-md-offset-3
  %h1.center Tic Tac Toe
  %div#game_board.center
    = render 'game_board'
  %br
  %h2#winner= win(GAME)
  %h2= link_to 'Restart game?', restart_game_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tic Tac Toe
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %div.container
      %div.row
        = yield